export enum NewsCategories{
    TOWN_NEWS='TOWN_NEWS',
    MUNICIPALITY_NEWS='MUNICIPALITY_NEWS',
    MUNICIPALITY_ANNOUNCEMENT='MUNICIPALITY_ANNOUNCEMENT',
    GENERAL_ANNOUNCEMENT='GENERAL_ANNOUNCEMENT',
    MUNICIPALITY_TRANSACTIONS='MUNICIPALITY_TRANSACTIONS',
    MUNICIPALITY_PROJECTS='MUNICIPALITY_PROJECTS',
    PLEASURES='PLEASURES',
    SADNESS='SADNESS',
    GENERAL_NEWS='GENERAL_NEWS'
}